services:
  backend:
    build:
      context: ./backend
    environment:
      - MONGODB_URL=MONGO_CLUSTER_URL
    container_name: backend
    ports:
      - "4000:4000"
    dns:
      - 8.8.8.8
      - 8.8.4.5

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
